services:
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 5173:5173
      - 6006:6006
    environment:
      CHOKIDAR_USEPOLLING: true
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/node_modules

volumes:
  node_modules:
    name: named-node_modules
